name: Release
on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [22]
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build extensions
        run: pnpm run build

      - name: Package extensions
        run: |
          cd dist && zip -r ../extensions.zip ./*

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: extensions.zip
          generate_release_notes: true
